apiVersion: v1
kind: Service
metadata:
  name: kronos-api
  namespace: default
  labels:
    app: kronos
    tier: backend
    version: v0.4.1
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: 4000
      name: http
  selector:
    app: kronos-api
